# Generated by Django 5.0 on 2023-12-08 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
                ('date_register', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=255, null=True)),
                ('institution_type', models.CharField(blank=True, max_length=255, null=True)),
                ('institution_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('institution_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('institution_address', models.TextField(blank=True, null=True)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('specialties', models.TextField(blank=True, null=True)),
                ('facilities', models.TextField(blank=True, null=True)),
                ('operating_hours', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('eventName', models.CharField(blank=True, max_length=255, null=True)),
                ('eventDescription', models.TextField(blank=True, null=True)),
                ('eventDate', models.DateField(blank=True, null=True)),
                ('eventTime', models.TimeField(blank=True, null=True)),
                ('eventLocation', models.CharField(blank=True, max_length=255, null=True)),
                ('eventDuration', models.CharField(blank=True, max_length=255, null=True)),
                ('eventOrganizer', models.CharField(blank=True, max_length=255, null=True)),
                ('eventOrganizerEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('eventOrganizerPhone', models.CharField(blank=True, max_length=255, null=True)),
                ('date_register', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
